

#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?



@pentagonals;

for(1 .. 10){
    push @pentagonals, pentagonal($_);
}

$i = $j = 0;
for $i (0 .. $#pentagonals){
    for $j ($i .. $#pentagonals){
        print "P" . ($i + 1) . " + P" . ($j + 1) . " = " . ($pentagonals[$i] + $pentagonals[$j]);
        print " x " if exist(($pentagonals[$i] + $pentagonals[$j]));
        print "\t\t";
        print "P" . ($i + 1) . " - P" . ($j + 1) . " = " . ($pentagonals[$i] - $pentagonals[$j]);
        print " x " if exist(($pentagonals[$i] - $pentagonals[$j]));
        print "\n";
    }
}

sub exist {
    my $x = shift;
    for(@pentagonals){
        return true if $_ == $x;
    }

    return false;
    
}

sub pentagonal {
    my $n = shift;
    return $n * (3*$n - 1) / 2;
}