/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n-1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/
#include <iostream>
#include <cmath>
#include <vector>
#include "../Utils/chrono.cpp"
#include "../Utils/iterators.cpp"


int t(int n){
	return (n * (n + 1)) / 2;
}

int p(int n){
	return (n * (3*n - 1)) / 2;
}

int h(int n){
	return n * (2*n - 1);
}


double inv_t(int t){
	return (std::sqrt(1 + 8*t) - 1) / 2;
}

double inv_p(int p){
	return (1 + std::sqrt(1 + 24*p)) / 6;
}

double inv_h(int h){
	return (1 + std::sqrt(1 + 8*h)) / 4;
}



int main(void){
	Chrono c;
	c.start();
	

	


	c.stop();
	std::cout << "Found the answer in " << c.time() << " seconds" << std::endl;
	return 0;
}

